export default {
  CREATE_FOLDER: "CREATE_FOLDER",
  DELETE_FOLDER: "DELETE_FOLDER",
  RENAME_FOLDER: "RENAME_FOLDER",
  CREATE_FILE: "CREATE_FILE",
  DELETE_FILE: "DELETE_FILE",
  RENAME_FILE: "RENAME_FILE",
};
